### ISSUE TITLE
Six dependency is causing an error

### ISSUE THREAD

**Issue by mikeIFTS** [IFTServices/django-pgviews#6]
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/circleci/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/circleci/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/circleci/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/circleci/.local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/circleci/.local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/ContractManager/src/django-pgviews/django_pgviews/models.py", line 6, in <module>
    from django_pgviews.view import create_view, View, MaterializedView
  File "/home/circleci/ContractManager/src/django-pgviews/django_pgviews/view.py", line 13, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/circleci/.local/lib/python3.7/site-packages/django/utils/__init__.py)
```

When updating from Django 2.2.9 -> 2.2.10, this issue popped up.

**Comment by mikeIFTS** [comment]
Seems like some work was done before this:
https://github.com/mypebble/django-pgviews/pull/54/commits/b18ee3214f5410a656b6ce69a17140733b4301c2

We can use this code and try it out.
